name: deep-sim
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=12.1
  - pyyaml
  - pip
variables:
  PYTHONNOUSERSITE: "1"
